/*
Deployment script for C:\USERS\SAMUKAWA_T1\DOCUMENTS\CODE\UAL\UNITED-AIRLINES-TRAINING-TEST\BAK.MDF

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "C:\USERS\SAMUKAWA_T1\DOCUMENTS\CODE\UAL\UNITED-AIRLINES-TRAINING-TEST\BAK.MDF"
:setvar DefaultFilePrefix "C_\USERS\SAMUKAWA_T1\DOCUMENTS\CODE\UAL\UNITED-AIRLINES-TRAINING-TEST\BAK.MDF_"
:setvar DefaultDataPath "C:\Users\Samukawa_T1\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"
:setvar DefaultLogPath "C:\Users\Samukawa_T1\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET AUTO_CLOSE OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
USE [$(DatabaseName)];


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET RECOVERY FULL,
                AUTO_SHRINK OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ALLOW_SNAPSHOT_ISOLATION ON;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET READ_COMMITTED_SNAPSHOT ON 
            WITH ROLLBACK IMMEDIATE;
    END


GO
ALTER DATABASE [$(DatabaseName)]
    SET TARGET_RECOVERY_TIME = 120 SECONDS 
    WITH ROLLBACK IMMEDIATE;


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET QUERY_STORE (QUERY_CAPTURE_MODE = AUTO, OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 7), MAX_STORAGE_SIZE_MB = 10) 
            WITH ROLLBACK IMMEDIATE;
    END


GO
PRINT N'Creating [dbo].[AdminAuditLog]...';


GO
CREATE TABLE [dbo].[AdminAuditLog] (
    [ID]         INT           NOT NULL,
    [Category]   VARCHAR (255) NOT NULL,
    [Item]       VARCHAR (255) NOT NULL,
    [Change]     VARCHAR (255) NOT NULL,
    [Username]   VARCHAR (255) NOT NULL,
    [UserRole]   VARCHAR (255) NOT NULL,
    [ChangeDate] DATETIME      NOT NULL,
    [MediaID]    INT           NULL,
    [Reverted]   BIT           NULL,
    PRIMARY KEY CLUSTERED ([ID] DESC)
);


GO
PRINT N'Creating [dbo].[ChangedChannel]...';


GO
CREATE TABLE [dbo].[ChangedChannel] (
    [ChangeID]    INT           NOT NULL,
    [ChannelID]   INT           NULL,
    [Title]       VARCHAR (100) NULL,
    [Description] VARCHAR (255) NULL,
    [Icon]        VARCHAR (255) NULL,
    [modifiedID]  INT           NULL,
    CONSTRAINT [PK_ChangedChannel] PRIMARY KEY CLUSTERED ([ChangeID] ASC)
);


GO
PRINT N'Creating [dbo].[ChangedComment]...';


GO
CREATE TABLE [dbo].[ChangedComment] (
    [ChangeID]    INT           NOT NULL,
    [UID]         VARCHAR (7)   NULL,
    [MediaID]     INT           NULL,
    [CommentID]   INT           NULL,
    [Description] VARCHAR (255) NULL,
    [Queued]      BIT           NULL,
    [CreatedAt]   DATETIME      NULL,
    CONSTRAINT [PK_ChangedComment] PRIMARY KEY CLUSTERED ([ChangeID] ASC)
);


GO
PRINT N'Creating [dbo].[ChangedMedia]...';


GO
CREATE TABLE [dbo].[ChangedMedia] (
    [ChangeID]           INT           NOT NULL,
    [MediaID]            INT           NULL,
    [MediaStatus]        VARCHAR (50)  NULL,
    [Title]              VARCHAR (100) NULL,
    [Description]        VARCHAR (255) NULL,
    [ThumbnailPath]      VARCHAR (255) NULL,
    [MediaTypeID]        INT           NULL,
    [Path]               VARCHAR (255) NULL,
    [FlaggedAllUsers]    BIT           NULL,
    [FlaggedLocations]   VARCHAR (500) NULL,
    [FlaggedJobCodes]    VARCHAR (500) NULL,
    [FlaggedDepartments] VARCHAR (500) NULL,
    [FlaggedJobGroups]   VARCHAR (500) NULL,
    [FlaggedCostCenters] VARCHAR (500) NULL,
    [CreatedAt]          DATETIME      NULL,
    CONSTRAINT [PK_ChangedMedia] PRIMARY KEY CLUSTERED ([ChangeID] ASC)
);


GO
PRINT N'Creating [dbo].[ChangedUser]...';


GO
CREATE TABLE [dbo].[ChangedUser] (
    [ChangeID]         INT           NOT NULL,
    [UID]              VARCHAR (7)   NULL,
    [FirstName]        VARCHAR (255) NULL,
    [LastName]         VARCHAR (255) NULL,
    [Email]            VARCHAR (255) NULL,
    [EmploymentStatus] VARCHAR (255) NULL,
    [Company]          VARCHAR (255) NULL,
    [RoleCode]         INT           NULL,
    [JobRoleCode]      VARCHAR (50)  NULL,
    [JobGroup]         VARCHAR (50)  NULL,
    [OccupationTitle]  VARCHAR (255) NULL,
    [Department]       VARCHAR (255) NULL,
    [LocationCode]     VARCHAR (50)  NULL,
    [CostCenter]       VARCHAR (50)  NULL,
    [CostCenterDesc]   VARCHAR (50)  NULL,
    [CreatedAt]        DATETIME      NULL,
    [UpdatedAt]        DATETIME      NULL,
    CONSTRAINT [PK_ChangedUser] PRIMARY KEY CLUSTERED ([ChangeID] ASC)
);


GO
PRINT N'Creating [dbo].[Channel]...';


GO
CREATE TABLE [dbo].[Channel] (
    [ChannelID]   INT           IDENTITY (1, 1) NOT NULL,
    [Title]       VARCHAR (100) NOT NULL,
    [Description] VARCHAR (255) NULL,
    [Icon]        VARCHAR (255) NULL,
    PRIMARY KEY CLUSTERED ([ChannelID] ASC)
);


GO
PRINT N'Creating [dbo].[ChannelKeyword]...';


GO
CREATE TABLE [dbo].[ChannelKeyword] (
    [ChannelID] INT NOT NULL,
    [KeywordID] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([ChannelID] ASC, [KeywordID] ASC)
);


GO
PRINT N'Creating [dbo].[Comment]...';


GO
CREATE TABLE [dbo].[Comment] (
    [UID]         VARCHAR (7)   NOT NULL,
    [MediaID]     INT           NOT NULL,
    [CommentID]   INT           IDENTITY (1, 1) NOT NULL,
    [Description] VARCHAR (255) NOT NULL,
    [Queued]      BIT           NULL,
    [CreatedAt]   DATETIME      NOT NULL,
    CONSTRAINT [PK__Comment__FCA4E7F6F894AAE7] PRIMARY KEY CLUSTERED ([UID] ASC, [MediaID] ASC, [CommentID] ASC)
);


GO
PRINT N'Creating [dbo].[GeneralFeedback]...';


GO
CREATE TABLE [dbo].[GeneralFeedback] (
    [GeneralFeedbackID] INT           IDENTITY (1, 1) NOT NULL,
    [UID]               VARCHAR (7)   NOT NULL,
    [Description]       VARCHAR (255) NOT NULL,
    [CreatedAt]         DATETIME      NOT NULL,
    CONSTRAINT [PK__GeneralF__326ECD30DAB45654] PRIMARY KEY CLUSTERED ([GeneralFeedbackID] ASC)
);


GO
PRINT N'Creating [dbo].[Keyword]...';


GO
CREATE TABLE [dbo].[Keyword] (
    [ID]   INT           IDENTITY (1, 1) NOT NULL,
    [Word] VARCHAR (100) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    UNIQUE NONCLUSTERED ([Word] ASC)
);


GO
PRINT N'Creating [dbo].[Media]...';


GO
CREATE TABLE [dbo].[Media] (
    [MediaID]            INT           IDENTITY (1, 1) NOT NULL,
    [MediaStatus]        VARCHAR (50)  NOT NULL,
    [Title]              VARCHAR (100) NOT NULL,
    [Description]        VARCHAR (255) NULL,
    [ThumbnailPath]      VARCHAR (255) NULL,
    [MediaTypeID]        INT           NOT NULL,
    [Path]               VARCHAR (255) NULL,
    [FlaggedAllUsers]    BIT           NULL,
    [FlaggedLocations]   VARCHAR (500) NULL,
    [FlaggedJobCodes]    VARCHAR (500) NULL,
    [FlaggedDepartments] VARCHAR (500) NULL,
    [FlaggedJobGroups]   VARCHAR (500) NULL,
    [FlaggedCostCenters] VARCHAR (500) NULL,
    [CreatedAt]          DATETIME      NOT NULL,
    CONSTRAINT [PK__Media__B2C2B5AF5CDFE93A] PRIMARY KEY CLUSTERED ([MediaID] ASC)
);


GO
PRINT N'Creating [dbo].[MediaFeedback]...';


GO
CREATE TABLE [dbo].[MediaFeedback] (
    [MediaFeedbackID] INT           IDENTITY (1, 1) NOT NULL,
    [MediaID]         INT           NOT NULL,
    [UID]             VARCHAR (7)   NOT NULL,
    [Description]     VARCHAR (255) NOT NULL,
    [CreatedAt]       DATETIME      NOT NULL,
    CONSTRAINT [PK_MediaFeedback] PRIMARY KEY CLUSTERED ([MediaFeedbackID] ASC)
);


GO
PRINT N'Creating [dbo].[MediaKeyword]...';


GO
CREATE TABLE [dbo].[MediaKeyword] (
    [MediaID]   INT NOT NULL,
    [KeywordID] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([MediaID] ASC, [KeywordID] ASC)
);


GO
PRINT N'Creating [dbo].[MediaToChannel]...';


GO
CREATE TABLE [dbo].[MediaToChannel] (
    [MediaID]   INT NOT NULL,
    [ChannelID] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([MediaID] ASC, [ChannelID] ASC)
);


GO
PRINT N'Creating [dbo].[MediaType]...';


GO
CREATE TABLE [dbo].[MediaType] (
    [ID]   INT           IDENTITY (1, 1) NOT NULL,
    [Name] VARCHAR (100) NOT NULL,
    [Icon] VARCHAR (255) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[NestedChannel]...';


GO
CREATE TABLE [dbo].[NestedChannel] (
    [ParentID] INT NOT NULL,
    [ChildID]  INT NOT NULL,
    PRIMARY KEY CLUSTERED ([ParentID] ASC, [ChildID] ASC)
);


GO
PRINT N'Creating [dbo].[Rating]...';


GO
CREATE TABLE [dbo].[Rating] (
    [UID]       VARCHAR (7) NOT NULL,
    [MediaID]   INT         NOT NULL,
    [Like]      BIT         NOT NULL,
    [CreatedAt] DATETIME    NOT NULL,
    CONSTRAINT [PK_Rating_1] PRIMARY KEY CLUSTERED ([UID] ASC, [MediaID] ASC)
);


GO
PRINT N'Creating [dbo].[Role]...';


GO
CREATE TABLE [dbo].[Role] (
    [RoleID]    INT          NOT NULL,
    [RoleLevel] VARCHAR (50) NULL,
    CONSTRAINT [PK_Role] PRIMARY KEY CLUSTERED ([RoleID] ASC)
);


GO
PRINT N'Creating [dbo].[Table]...';


GO
CREATE TABLE [dbo].[Table] (
    [Id] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[TechTalkSession]...';


GO
CREATE TABLE [dbo].[TechTalkSession] (
    [ID]      INT           IDENTITY (1, 1) NOT NULL,
    [URLPath] VARCHAR (255) NOT NULL,
    [Time]    DATETIME      NOT NULL,
    [MediaID] INT           NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO
PRINT N'Creating [dbo].[User]...';


GO
CREATE TABLE [dbo].[User] (
    [UID]              VARCHAR (7)   NOT NULL,
    [FirstName]        VARCHAR (255) NULL,
    [LastName]         VARCHAR (255) NULL,
    [Email]            VARCHAR (255) NULL,
    [EmploymentStatus] VARCHAR (255) NULL,
    [Company]          VARCHAR (255) NULL,
    [RoleCode]         INT           NOT NULL,
    [JobRoleCode]      VARCHAR (50)  NULL,
    [JobGroup]         VARCHAR (50)  NULL,
    [OccupationTitle]  VARCHAR (255) NULL,
    [Department]       VARCHAR (255) NULL,
    [LocationCode]     VARCHAR (50)  NULL,
    [CostCenter]       VARCHAR (50)  NULL,
    [CostCenterDesc]   VARCHAR (50)  NULL,
    [CreatedAt]        DATETIME      NOT NULL,
    [UpdatedAt]        DATETIME      NOT NULL,
    CONSTRAINT [PK__User__1788CCAC22C7AE23] PRIMARY KEY CLUSTERED ([UID] ASC)
);


GO
PRINT N'Creating [dbo].[UserHistory]...';


GO
CREATE TABLE [dbo].[UserHistory] (
    [UID]           VARCHAR (7) NOT NULL,
    [MediaID]       INT         NOT NULL,
    [WatchLength]   REAL        NOT NULL,
    [ClickedAmount] INT         NOT NULL,
    [CreatedAt]     DATETIME    NOT NULL,
    [CompleteView]  BIT         NOT NULL,
    [UpdatedAt]     DATETIME    NULL,
    CONSTRAINT [PK__UserHist__FCA4E7F61F3EBD54] PRIMARY KEY CLUSTERED ([UID] ASC, [MediaID] ASC)
);


GO
PRINT N'Creating unnamed constraint on [dbo].[AdminAuditLog]...';


GO
ALTER TABLE [dbo].[AdminAuditLog]
    ADD DEFAULT ((0)) FOR [Reverted];


GO
PRINT N'Creating [dbo].[FK_ChannelKeyword_Channel]...';


GO
ALTER TABLE [dbo].[ChannelKeyword] WITH NOCHECK
    ADD CONSTRAINT [FK_ChannelKeyword_Channel] FOREIGN KEY ([ChannelID]) REFERENCES [dbo].[Channel] ([ChannelID]) ON DELETE CASCADE ON UPDATE CASCADE;


GO
PRINT N'Creating [dbo].[FK_ChannelKeyword_Keyword]...';


GO
ALTER TABLE [dbo].[ChannelKeyword] WITH NOCHECK
    ADD CONSTRAINT [FK_ChannelKeyword_Keyword] FOREIGN KEY ([KeywordID]) REFERENCES [dbo].[Keyword] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE;


GO
PRINT N'Creating [dbo].[FK_Comment_Media]...';


GO
ALTER TABLE [dbo].[Comment] WITH NOCHECK
    ADD CONSTRAINT [FK_Comment_Media] FOREIGN KEY ([MediaID]) REFERENCES [dbo].[Media] ([MediaID]) ON DELETE CASCADE ON UPDATE CASCADE;


GO
PRINT N'Creating [dbo].[FK_Comment_User]...';


GO
ALTER TABLE [dbo].[Comment] WITH NOCHECK
    ADD CONSTRAINT [FK_Comment_User] FOREIGN KEY ([UID]) REFERENCES [dbo].[User] ([UID]) ON DELETE CASCADE ON UPDATE CASCADE;


GO
PRINT N'Creating [dbo].[FK_GeneralFeedback_User]...';


GO
ALTER TABLE [dbo].[GeneralFeedback] WITH NOCHECK
    ADD CONSTRAINT [FK_GeneralFeedback_User] FOREIGN KEY ([UID]) REFERENCES [dbo].[User] ([UID]);


GO
PRINT N'Creating [dbo].[FK__Media__MediaType__3587F3E0]...';


GO
ALTER TABLE [dbo].[Media] WITH NOCHECK
    ADD CONSTRAINT [FK__Media__MediaType__3587F3E0] FOREIGN KEY ([MediaTypeID]) REFERENCES [dbo].[MediaType] ([ID]);


GO
PRINT N'Creating [dbo].[FK_MediaFeedback_Media]...';


GO
ALTER TABLE [dbo].[MediaFeedback] WITH NOCHECK
    ADD CONSTRAINT [FK_MediaFeedback_Media] FOREIGN KEY ([MediaID]) REFERENCES [dbo].[Media] ([MediaID]) ON DELETE CASCADE ON UPDATE CASCADE;


GO
PRINT N'Creating [dbo].[FK_MediaFeedback_User]...';


GO
ALTER TABLE [dbo].[MediaFeedback] WITH NOCHECK
    ADD CONSTRAINT [FK_MediaFeedback_User] FOREIGN KEY ([UID]) REFERENCES [dbo].[User] ([UID]);


GO
PRINT N'Creating [dbo].[FK_MediaKeyword_Keyword]...';


GO
ALTER TABLE [dbo].[MediaKeyword] WITH NOCHECK
    ADD CONSTRAINT [FK_MediaKeyword_Keyword] FOREIGN KEY ([KeywordID]) REFERENCES [dbo].[Keyword] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE;


GO
PRINT N'Creating [dbo].[FK_MediaKeyword_Media]...';


GO
ALTER TABLE [dbo].[MediaKeyword] WITH NOCHECK
    ADD CONSTRAINT [FK_MediaKeyword_Media] FOREIGN KEY ([MediaID]) REFERENCES [dbo].[Media] ([MediaID]) ON DELETE CASCADE ON UPDATE CASCADE;


GO
PRINT N'Creating [dbo].[FK_MediaToChannel_Channel]...';


GO
ALTER TABLE [dbo].[MediaToChannel] WITH NOCHECK
    ADD CONSTRAINT [FK_MediaToChannel_Channel] FOREIGN KEY ([ChannelID]) REFERENCES [dbo].[Channel] ([ChannelID]) ON DELETE CASCADE ON UPDATE CASCADE;


GO
PRINT N'Creating [dbo].[FK_MediaToChannel_Media]...';


GO
ALTER TABLE [dbo].[MediaToChannel] WITH NOCHECK
    ADD CONSTRAINT [FK_MediaToChannel_Media] FOREIGN KEY ([MediaID]) REFERENCES [dbo].[Media] ([MediaID]) ON DELETE CASCADE ON UPDATE CASCADE;


GO
PRINT N'Creating [dbo].[FK_NestedChannel_ChannelChild]...';


GO
ALTER TABLE [dbo].[NestedChannel] WITH NOCHECK
    ADD CONSTRAINT [FK_NestedChannel_ChannelChild] FOREIGN KEY ([ChildID]) REFERENCES [dbo].[Channel] ([ChannelID]);


GO
PRINT N'Creating [dbo].[FK_NestedChannel_ChannelParent]...';


GO
ALTER TABLE [dbo].[NestedChannel] WITH NOCHECK
    ADD CONSTRAINT [FK_NestedChannel_ChannelParent] FOREIGN KEY ([ParentID]) REFERENCES [dbo].[Channel] ([ChannelID]) ON DELETE CASCADE ON UPDATE CASCADE;


GO
PRINT N'Creating [dbo].[FK_Rating_Media]...';


GO
ALTER TABLE [dbo].[Rating] WITH NOCHECK
    ADD CONSTRAINT [FK_Rating_Media] FOREIGN KEY ([MediaID]) REFERENCES [dbo].[Media] ([MediaID]) ON DELETE CASCADE ON UPDATE CASCADE;


GO
PRINT N'Creating [dbo].[FK_Rating_User]...';


GO
ALTER TABLE [dbo].[Rating] WITH NOCHECK
    ADD CONSTRAINT [FK_Rating_User] FOREIGN KEY ([UID]) REFERENCES [dbo].[User] ([UID]) ON DELETE CASCADE ON UPDATE CASCADE;


GO
PRINT N'Creating [dbo].[FK_TechTalkSession_Media]...';


GO
ALTER TABLE [dbo].[TechTalkSession] WITH NOCHECK
    ADD CONSTRAINT [FK_TechTalkSession_Media] FOREIGN KEY ([MediaID]) REFERENCES [dbo].[Media] ([MediaID]) ON DELETE CASCADE ON UPDATE CASCADE;


GO
PRINT N'Creating [dbo].[FK_User_Role]...';


GO
ALTER TABLE [dbo].[User] WITH NOCHECK
    ADD CONSTRAINT [FK_User_Role] FOREIGN KEY ([RoleCode]) REFERENCES [dbo].[Role] ([RoleID]);


GO
PRINT N'Creating [dbo].[FK__UserHisto__Media__3D2915A8]...';


GO
ALTER TABLE [dbo].[UserHistory] WITH NOCHECK
    ADD CONSTRAINT [FK__UserHisto__Media__3D2915A8] FOREIGN KEY ([MediaID]) REFERENCES [dbo].[Media] ([MediaID]) ON DELETE CASCADE;


GO
PRINT N'Creating [dbo].[FK__UserHisto__UserI__3C34F16F]...';


GO
ALTER TABLE [dbo].[UserHistory] WITH NOCHECK
    ADD CONSTRAINT [FK__UserHisto__UserI__3C34F16F] FOREIGN KEY ([UID]) REFERENCES [dbo].[User] ([UID]) ON DELETE CASCADE;


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[ChannelKeyword] WITH CHECK CHECK CONSTRAINT [FK_ChannelKeyword_Channel];

ALTER TABLE [dbo].[ChannelKeyword] WITH CHECK CHECK CONSTRAINT [FK_ChannelKeyword_Keyword];

ALTER TABLE [dbo].[Comment] WITH CHECK CHECK CONSTRAINT [FK_Comment_Media];

ALTER TABLE [dbo].[Comment] WITH CHECK CHECK CONSTRAINT [FK_Comment_User];

ALTER TABLE [dbo].[GeneralFeedback] WITH CHECK CHECK CONSTRAINT [FK_GeneralFeedback_User];

ALTER TABLE [dbo].[Media] WITH CHECK CHECK CONSTRAINT [FK__Media__MediaType__3587F3E0];

ALTER TABLE [dbo].[MediaFeedback] WITH CHECK CHECK CONSTRAINT [FK_MediaFeedback_Media];

ALTER TABLE [dbo].[MediaFeedback] WITH CHECK CHECK CONSTRAINT [FK_MediaFeedback_User];

ALTER TABLE [dbo].[MediaKeyword] WITH CHECK CHECK CONSTRAINT [FK_MediaKeyword_Keyword];

ALTER TABLE [dbo].[MediaKeyword] WITH CHECK CHECK CONSTRAINT [FK_MediaKeyword_Media];

ALTER TABLE [dbo].[MediaToChannel] WITH CHECK CHECK CONSTRAINT [FK_MediaToChannel_Channel];

ALTER TABLE [dbo].[MediaToChannel] WITH CHECK CHECK CONSTRAINT [FK_MediaToChannel_Media];

ALTER TABLE [dbo].[NestedChannel] WITH CHECK CHECK CONSTRAINT [FK_NestedChannel_ChannelChild];

ALTER TABLE [dbo].[NestedChannel] WITH CHECK CHECK CONSTRAINT [FK_NestedChannel_ChannelParent];

ALTER TABLE [dbo].[Rating] WITH CHECK CHECK CONSTRAINT [FK_Rating_Media];

ALTER TABLE [dbo].[Rating] WITH CHECK CHECK CONSTRAINT [FK_Rating_User];

ALTER TABLE [dbo].[TechTalkSession] WITH CHECK CHECK CONSTRAINT [FK_TechTalkSession_Media];

ALTER TABLE [dbo].[User] WITH CHECK CHECK CONSTRAINT [FK_User_Role];

ALTER TABLE [dbo].[UserHistory] WITH CHECK CHECK CONSTRAINT [FK__UserHisto__Media__3D2915A8];

ALTER TABLE [dbo].[UserHistory] WITH CHECK CHECK CONSTRAINT [FK__UserHisto__UserI__3C34F16F];


GO
PRINT N'Update complete.';


GO
